import { StyleSheet } from "react-native";
import {
  COLORS,
  FONT_SIZES,
  IMAGE_HEIGHT,
  MIN_TOUCH_TARGET,
  SPACING,
} from "./constants";

export const historyStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.GRAY_50,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: COLORS.GRAY_50,
  },
  loadingText: {
    marginTop: SPACING.MD,
    fontSize: FONT_SIZES.MD,
    color: COLORS.GRAY_400,
  },
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: COLORS.GRAY_50,
    paddingHorizontal: SPACING.XXXL,
  },
  errorTitle: {
    fontSize: FONT_SIZES.XL,
    fontWeight: "600",
    color: COLORS.GRAY_700,
    marginTop: SPACING.LG,
    marginBottom: SPACING.SM,
  },
  errorSubtitle: {
    fontSize: FONT_SIZES.SM,
    color: COLORS.GRAY_400,
    textAlign: "center",
    lineHeight: 20,
    marginBottom: SPACING.XXL,
  },
  retryButton: {
    backgroundColor: COLORS.PRIMARY,
    paddingHorizontal: SPACING.XXL,
    paddingVertical: SPACING.MD,
    borderRadius: SPACING.SM,
    minHeight: MIN_TOUCH_TARGET,
    justifyContent: "center",
  },
  retryButtonText: {
    color: COLORS.WHITE,
    fontSize: FONT_SIZES.MD,
    fontWeight: "600",
  },
  header: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: SPACING.XL,
    paddingTop: 26,
    paddingBottom: SPACING.LG,
    gap: SPACING.XS,
  },
  title: {
    fontSize: FONT_SIZES.XXL,
    fontWeight: "bold",
    color: COLORS.GRAY_900,
  },
  clearButton: {
    padding: SPACING.SM,
    minHeight: MIN_TOUCH_TARGET,
    minWidth: MIN_TOUCH_TARGET,
    justifyContent: "center",
    alignItems: "center",
  },
  flatListContent: {
    paddingBottom: 100,
  },
  statsContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    paddingHorizontal: SPACING.XL,
    marginBottom: SPACING.XL,
  },
  statItem: {
    alignItems: "center",
    minHeight: MIN_TOUCH_TARGET,
    justifyContent: "center",
  },
  statNumber: {
    fontSize: FONT_SIZES.XXL,
    fontWeight: "bold",
    color: COLORS.PRIMARY,
  },
  statLabel: {
    fontSize: FONT_SIZES.XS,
    color: COLORS.GRAY_400,
    marginTop: SPACING.XS,
  },
  chartContainer: {
    paddingHorizontal: SPACING.XL,
    marginBottom: SPACING.XL,
  },
  chartTitle: {
    fontSize: FONT_SIZES.MD,
    fontWeight: "600",
    color: COLORS.GRAY_700,
    marginBottom: SPACING.MD,
  },
  chart: {
    borderRadius: SPACING.MD,
    backgroundColor: COLORS.WHITE,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  predictionItem: {
    backgroundColor: COLORS.WHITE,
    borderRadius: SPACING.MD,
    marginBottom: SPACING.LG,
    marginHorizontal: SPACING.XL,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    overflow: "hidden",
  },
  imageContainer: {
    position: "relative",
    height: IMAGE_HEIGHT,
  },
  imageLoadingContainer: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: COLORS.GRAY_100,
    zIndex: 1,
  },
  predictionImage: {
    width: "100%",
    height: IMAGE_HEIGHT,
  },
  hiddenImage: {
    opacity: 0,
  },
  confidenceBadge: {
    position: "absolute",
    top: SPACING.MD,
    right: SPACING.MD,
    paddingHorizontal: SPACING.SM,
    paddingVertical: SPACING.XS,
    borderRadius: 6,
    minHeight: 24,
    justifyContent: "center",
  },
  confidenceText: {
    color: COLORS.WHITE,
    fontSize: FONT_SIZES.XS,
    fontWeight: "bold",
  },
  predictionDetails: {
    padding: SPACING.LG,
  },
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: SPACING.SM,
  },
  cropName: {
    fontSize: FONT_SIZES.LG,
    fontWeight: "600",
    color: COLORS.GRAY_900,
    flex: 1,
    marginRight: SPACING.SM,
  },
  timestamp: {
    fontSize: FONT_SIZES.XS,
    color: COLORS.GRAY_400,
  },
  diseaseName: {
    fontSize: FONT_SIZES.MD,
    fontWeight: "500",
    marginBottom: SPACING.SM,
  },
  riskContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: SPACING.XS,
  },
  riskLevel: {
    fontSize: FONT_SIZES.SM,
    fontWeight: "500",
    marginLeft: SPACING.XS,
  },
  confidenceLevel: {
    fontSize: FONT_SIZES.XS,
    color: COLORS.GRAY_400,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: SPACING.XXXL,
  },
  emptyTitle: {
    fontSize: FONT_SIZES.XL,
    fontWeight: "600",
    color: COLORS.GRAY_700,
    marginTop: SPACING.LG,
    marginBottom: SPACING.SM,
  },
  emptySubtitle: {
    fontSize: FONT_SIZES.SM,
    color: COLORS.GRAY_400,
    textAlign: "center",
    lineHeight: 20,
  },
  loadMoreContainer: {
    padding: SPACING.XL,
    alignItems: "center",
  },
  loadMoreText: {
    marginTop: SPACING.SM,
    fontSize: FONT_SIZES.SM,
    color: COLORS.GRAY_400,
  },
});
