import { Dimensions, StyleSheet } from "react-native";
const screenHeight = Dimensions.get("window").height;

export const stylesScan = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#000",
  },
  permissionContainer: {
    flex: 1,
    backgroundColor: "#f8f9fa",
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
  },
  permissionText: {
    fontSize: 18,
    fontWeight: "600",
    textAlign: "center",
    marginTop: 20,
    marginBottom: 8,
    color: "#333",
  },
  permissionSubText: {
    fontSize: 14,
    textAlign: "center",
    color: "#666",
    marginBottom: 30,
  },
  permissionButton: {
    backgroundColor: "#4CAF50",
    paddingHorizontal: 30,
    paddingVertical: 15,
    borderRadius: 25,
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  permissionButtonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "600",
  },
  camera: {
    flex: 1,
    width: "100%",
  },
  backButtonCamera: {
    position: "absolute",
    top: 50,
    left: 20,
    zIndex: 1000,
    backgroundColor: "rgba(0,0,0,0.5)",
    borderRadius: 20,
    padding: 10,
  },
  backButton: {
    position: "absolute",
    top: 50,
    left: 20,
    zIndex: 1000,
    backgroundColor: "rgba(0,0,0,0.7)",
    borderRadius: 20,
    padding: 10,
  },
  cameraOverlay: {
    position: "absolute",
    top: 100,
    left: 0,
    right: 0,
    alignItems: "center",
    paddingHorizontal: 20,
  },
  instructionText: {
    color: "white",
    fontSize: 16,
    textAlign: "center",
    backgroundColor: "rgba(0,0,0,0.5)",
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderRadius: 20,
  },
  cameraControls: {
    position: "absolute",
    bottom: 40,
    left: 0,
    right: 0,
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    paddingHorizontal: 30,
  },
  cameraButton: {
    backgroundColor: "rgba(255,255,255,0.2)",
    borderRadius: 30,
    padding: 15,
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.3)",
  },
  shutterButton: {
    backgroundColor: "transparent",
    borderWidth: 4,
    borderColor: "white",
    width: 80,
    height: 80,
    borderRadius: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  shutterButtonInner: {
    backgroundColor: "white",
    width: 65,
    height: 65,
    borderRadius: 32.5,
  },
  imageContainer: {
    flex: 1,
    backgroundColor: "#000",
  },
  capturedImage: {
    width: "100%",
    height: screenHeight * 0.4,
    marginTop: 80,
  },
  imageControlsContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    paddingVertical: 20,
    paddingHorizontal: 20,
    backgroundColor: "rgba(0,0,0,0.8)",
  },
  controlButton: {
    alignItems: "center",
    padding: 10,
  },
  controlButtonText: {
    color: "white",
    fontSize: 12,
    marginTop: 4,
  },
  sendButton: {
    backgroundColor: "#4CAF50",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 25,
    elevation: 3,
  },
  sendButtonDisabled: {
    backgroundColor: "#757575",
  },
  sendButtonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "600",
    marginLeft: 8,
  },
  resultsContainer: {
    flex: 1,
    backgroundColor: "#f5f5f5",
  },
  resultCard: {
    backgroundColor: "white",
    margin: 15,
    padding: 20,
    borderRadius: 15,
    elevation: 3,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  resultTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 20,
    textAlign: "center",
    borderBottomWidth: 1,
    borderBottomColor: "#e0e0e0",
    paddingBottom: 10,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#2196F3",
    marginBottom: 10,
    marginTop: 5,
  },
  resultRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
    alignItems: "flex-start",
  },
  resultLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: "#666",
    flex: 1,
    marginRight: 10,
  },
  resultValue: {
    fontSize: 14,
    color: "#333",
    flex: 2,
    textAlign: "right",
  },
  divider: {
    height: 1,
    backgroundColor: "#e0e0e0",
    marginVertical: 15,
  },
  descriptionContainer: {
    marginTop: 15,
    marginBottom: 10,
  },
  descriptionText: {
    fontSize: 14,
    color: "#555",
    lineHeight: 22,
    marginTop: 5,
    textAlign: "justify",
  },
  recommendationsContainer: {
    marginTop: 10,
  },
  recommendationItem: {
    fontSize: 14,
    color: "#2E7D32",
    lineHeight: 22,
    marginTop: 5,
    paddingLeft: 5,
  },
  symptomItem: {
    fontSize: 14,
    color: "#F57C00",
    lineHeight: 22,
    marginTop: 3,
    paddingLeft: 5,
  },
  treatmentItem: {
    fontSize: 14,
    color: "#1976D2",
    lineHeight: 22,
    marginTop: 3,
    paddingLeft: 5,
  },
  preventionItem: {
    fontSize: 14,
    color: "#388E3C",
    lineHeight: 22,
    marginTop: 3,
    paddingLeft: 5,
  },
  allPredictionsContainer: {
    marginTop: 10,
  },
  alternativeRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 6,
    paddingHorizontal: 10,
    backgroundColor: "#f8f9fa",
    borderRadius: 8,
    marginTop: 5,
  },
  alternativeClass: {
    fontSize: 13,
    color: "#666",
    flex: 1,
  },
  alternativeConfidence: {
    fontSize: 13,
    color: "#888",
    fontWeight: "500",
  },
});
